// Runtime API acceptance gate. Runs the test suite with the response recorder enabled
// (API_COVERAGE_FILE), then checks that every operation in openapi/openapi.json saw at least one
// success (2xx/3xx) and one failure (4xx), unless tests/acceptance/not-applicable.ts says why not.
// Writes docs/migration/api-coverage.md. `--no-run` re-analyses the last recording.
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { format, resolveConfig } from "prettier";
import { NOT_APPLICABLE } from "../tests/acceptance/not-applicable.js";

const RECORDING = resolve("coverage/api-calls.jsonl");
const REPORT = "docs/migration/api-coverage.md";
const METHODS = ["get", "post", "put", "patch", "delete"] as const;

type Observed = { success: Set<number>; failure: Set<number> };
type Row = { key: string; success: string; failure: string; ok: boolean };

if (!process.argv.includes("--no-run")) {
  mkdirSync("coverage", { recursive: true });
  rmSync(RECORDING, { force: true });
  const run = spawnSync("npx", ["vitest", "run"], {
    stdio: "inherit",
    env: { ...process.env, API_COVERAGE_FILE: RECORDING },
  });
  if (run.status !== 0) {
    console.error("Test suite failed; coverage not evaluated.");
    process.exit(run.status ?? 1);
  }
}
if (!existsSync(RECORDING)) {
  console.error(`No recording at ${RECORDING}. Run without --no-run first.`);
  process.exit(1);
}

const document = JSON.parse(readFileSync("openapi/openapi.json", "utf8")) as {
  paths: Record<string, Partial<Record<(typeof METHODS)[number], unknown>>>;
};
const operations: string[] = [];
for (const [path, item] of Object.entries(document.paths))
  for (const method of METHODS)
    if (item[method]) operations.push(`${method.toUpperCase()} ${path}`);

const observed = new Map<string, Observed>();
for (const line of readFileSync(RECORDING, "utf8").split("\n")) {
  if (!line.trim()) continue;
  const { method, path, status } = JSON.parse(line) as {
    method: string;
    path: string;
    status: number;
  };
  const key = `${method} ${path.replace(/:([A-Za-z0-9_]+)/g, "{$1}")}`;
  const entry = observed.get(key) ?? { success: new Set(), failure: new Set() };
  if (status >= 200 && status < 400) entry.success.add(status);
  else if (status >= 400 && status < 500) entry.failure.add(status);
  observed.set(key, entry);
}

const statuses = (set: Set<number>) => [...set].sort().join(", ");
const problems: string[] = [];
const rows: Row[] = operations.map((key) => {
  const seen = observed.get(key);
  const na = NOT_APPLICABLE[key];
  const cell = (kind: "success" | "failure") => {
    const set = seen?.[kind];
    if (set?.size) return `✓ ${statuses(set)}`;
    if (na?.[kind]) return `N.A. ${na[kind]}`;
    problems.push(`${key}: no ${kind} case`);
    return "**MISSING**";
  };
  const success = cell("success");
  const failure = cell("failure");
  return {
    key,
    success,
    failure,
    ok: !success.includes("MISSING") && !failure.includes("MISSING"),
  };
});
for (const key of Object.keys(NOT_APPLICABLE))
  if (!operations.includes(key))
    problems.push(`not-applicable entry for unknown operation: ${key}`);

const count = (pred: (row: Row) => boolean) => rows.filter(pred).length;
const summary = {
  total: rows.length,
  success: count((r) => r.success.startsWith("✓")),
  failure: count((r) => r.failure.startsWith("✓")),
  successNa: count((r) => r.success.startsWith("N.A.")),
  failureNa: count((r) => r.failure.startsWith("N.A.")),
  complete: count((r) => r.ok),
};
const escape = (text: string) => text.replace(/\|/g, "\\|");
const markdown = [
  "# API coverage",
  "",
  "Generated by `npm run test:api-coverage` (`scripts/api-coverage.ts`). The integration suite",
  "runs against a Testcontainers PostgreSQL built from migrations; every `/api/v1` response is",
  "recorded with its route pattern and status. Success = any 2xx/3xx observed, failure = any 4xx",
  "observed. Gaps are allowed only with a reason in `tests/acceptance/not-applicable.ts`.",
  "",
  `- Operations: ${summary.total}`,
  `- Success covered: ${summary.success} (N.A.: ${summary.successNa})`,
  `- Failure covered: ${summary.failure} (N.A.: ${summary.failureNa})`,
  `- Complete (both columns ✓ or N.A.): ${summary.complete}/${summary.total}`,
  "",
  "| Operation | Success | Failure |",
  "| --- | --- | --- |",
  ...rows.map((r) => `| \`${r.key}\` | ${escape(r.success)} | ${escape(r.failure)} |`),
  "",
  "## Not applicable",
  "",
  ...(Object.keys(NOT_APPLICABLE).length
    ? Object.entries(NOT_APPLICABLE).flatMap(([key, reasons]) =>
        Object.entries(reasons).map(([kind, reason]) => `- \`${key}\` (${kind}): ${reason}`),
      )
    : ["None: every operation has an observed success and an observed failure case."]),
  "",
].join("\n");
writeFileSync(
  REPORT,
  await format(markdown, { ...(await resolveConfig(REPORT)), filepath: REPORT }),
);

console.log(
  `API coverage: ${summary.total} operations, success ${summary.success} (+${summary.successNa} N.A.), ` +
    `failure ${summary.failure} (+${summary.failureNa} N.A.). Report: ${REPORT}`,
);
if (problems.length) {
  console.error(`\n${problems.length} coverage gap(s):\n  ${problems.join("\n  ")}`);
  process.exit(1);
}
