import { z } from "zod";
import { defineRoute } from "../../shared/http/route.js";
import * as schemas from "./projects.schemas.js";
import * as service from "./projects.service.js";

const tags = ["projects"];

export const projectRoutes = [
  defineRoute({
    method: "get",
    path: "/projects",
    operationId: "listProjects",
    summary: "Projects the caller can read, newest first (archived ones included)",
    tags,
    response: { status: 200, schema: z.array(schemas.projectSchema) },
    handler: ({ actor }) => service.listVisibleProjects(actor),
  }),
  defineRoute({
    method: "post",
    path: "/projects",
    operationId: "createProject",
    summary: "Create a project in an account the caller administers",
    tags,
    request: { body: schemas.createProjectBody },
    response: { status: 201, schema: schemas.projectSchema },
    errors: [403, 409],
    handler: ({ actor, body }) => service.createProject(actor, body),
  }),
  defineRoute({
    method: "get",
    path: "/projects/stats",
    operationId: "getProjectStats",
    summary: "Ticket, sprint and member counts for visible projects",
    tags,
    request: { query: schemas.idsQuery },
    response: { status: 200, schema: z.array(schemas.projectStatsSchema) },
    handler: ({ actor, query }) => service.getProjectStats(actor, query.ids),
  }),
  defineRoute({
    method: "patch",
    path: "/projects/:projectId",
    operationId: "updateProject",
    summary: "Edit project details (project managers)",
    tags,
    request: { params: schemas.projectIdParams, body: schemas.updateProjectBody },
    response: { status: 200, schema: schemas.projectSchema },
    errors: [403, 404, 409],
    handler: ({ actor, params, body }) => service.updateProject(actor, params.projectId, body),
  }),
  defineRoute({
    method: "delete",
    path: "/projects/:projectId",
    operationId: "deleteProject",
    summary: "Permanently delete a project and its content (account admins)",
    tags,
    request: { params: schemas.projectIdParams },
    response: { status: 204 },
    errors: [403, 404],
    handler: ({ actor, params }) => service.deleteProject(actor, params.projectId),
  }),
  defineRoute({
    method: "post",
    path: "/projects/:projectId/archive",
    operationId: "archiveProject",
    summary: "Archive a project (read-only, hidden from members)",
    tags,
    request: { params: schemas.projectIdParams },
    response: { status: 200, schema: schemas.projectSchema },
    errors: [403, 404],
    handler: ({ actor, params }) => service.setArchived(actor, params.projectId, true),
  }),
  defineRoute({
    method: "post",
    path: "/projects/:projectId/restore",
    operationId: "restoreProject",
    summary: "Restore an archived project",
    tags,
    request: { params: schemas.projectIdParams },
    response: { status: 200, schema: schemas.projectSchema },
    errors: [403, 404],
    handler: ({ actor, params }) => service.setArchived(actor, params.projectId, false),
  }),
  defineRoute({
    method: "post",
    path: "/projects/:projectId/move",
    operationId: "moveProject",
    summary: "Move a project to another account (admin of both accounts)",
    tags,
    request: { params: schemas.projectIdParams, body: schemas.moveProjectBody },
    response: { status: 200, schema: schemas.projectSchema },
    errors: [403, 404, 409],
    handler: ({ actor, params, body }) =>
      service.moveProject(actor, params.projectId, body.accountId),
  }),
  defineRoute({
    method: "get",
    path: "/projects/:projectId/people",
    operationId: "listProjectPeople",
    summary:
      "People who can access the project: members and account admins (no archived users or super admins)",
    tags,
    request: { params: schemas.projectIdParams },
    response: { status: 200, schema: z.array(schemas.accessibleUserSchema) },
    errors: [404],
    handler: ({ actor, params }) => service.listProjectPeople(actor, params.projectId),
  }),
  defineRoute({
    method: "get",
    path: "/rate-card",
    operationId: "listRateCard",
    summary: "Rate card rows for the given visible projects",
    tags: ["rate-card"],
    request: { query: schemas.idsQuery },
    response: { status: 200, schema: z.array(schemas.rateSchema) },
    handler: ({ actor, query }) => service.listRates(actor, query.ids),
  }),
  defineRoute({
    method: "post",
    path: "/projects/:projectId/rate-card",
    operationId: "createRate",
    summary: "Add a rate (project managers)",
    tags: ["rate-card"],
    request: { params: schemas.projectIdParams, body: schemas.rateBody },
    response: { status: 201, schema: schemas.rateSchema },
    errors: [403, 404, 409],
    handler: ({ actor, params, body }) => service.createRate(actor, params.projectId, body),
  }),
  defineRoute({
    method: "put",
    path: "/projects/:projectId/rate-card/:rateId",
    operationId: "updateRate",
    summary: "Change a rate (project managers)",
    tags: ["rate-card"],
    request: { params: schemas.rateParams, body: schemas.rateBody },
    response: { status: 200, schema: schemas.rateSchema },
    errors: [403, 404, 409],
    handler: ({ actor, params, body }) =>
      service.updateRate(actor, params.projectId, params.rateId, body),
  }),
  defineRoute({
    method: "delete",
    path: "/projects/:projectId/rate-card/:rateId",
    operationId: "deleteRate",
    summary: "Remove a rate (project managers)",
    tags: ["rate-card"],
    request: { params: schemas.rateParams },
    response: { status: 204 },
    errors: [403, 404],
    handler: ({ actor, params }) => service.deleteRate(actor, params.projectId, params.rateId),
  }),
];
